theme: jekyll-theme-slate
title: MQTT2GO Convention
description: An agreement between interested parties covering application specific positions, definitions and specifications for harmonised MQTT applications.
