theme: jekyll-theme-slate
title: MQTT2GO Convention
description: An agreement on positions, definitions and specifications for MQTT in a harmonised form for service platforms, IoT devices and user applications.
